<?php
/**
 * TodolistApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API TodoList application
 *
 * Test create swagger documentation application TodoList
 *
 * OpenAPI spec version: 1.0
 * Contact: thoyibh07@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * TodolistApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TodolistApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for todolistGet
     *
     * Get All Todolist.
     *
     */
    public function testTodolistGet()
    {
    }

    /**
     * Test case for todolistPost
     *
     * Create new todolist.
     *
     */
    public function testTodolistPost()
    {
    }

    /**
     * Test case for todolistTodolistIdDelete
     *
     * Delete existing todolist.
     *
     */
    public function testTodolistTodolistIdDelete()
    {
    }

    /**
     * Test case for todolistTodolistIdPut
     *
     * Update existing todolist.
     *
     */
    public function testTodolistTodolistIdPut()
    {
    }
}
