/*
 * API TodoList application
 *
 * Test create swagger documentation application TodoList
 *
 * API version: 1.0
 * Contact: thoyibh07@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {
	Success bool `json:"success,omitempty"`
}
