/*
 * API TodoList application
 *
 * Test create swagger documentation application TodoList
 *
 * API version: 1.0
 * Contact: thoyibh07@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateOrUpdateTodolist struct {
	Name string `json:"name,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Priority int32 `json:"priority,omitempty"`
}
